### ISSUE TITLE
Coherence rule changes in latest nightly break parser-combinators

### ISSUE THREAD

**Issue by hugoduncan** [Marwes/parser-combinators#27]
The `impl`s for `Stream` for `&str` and `&[T]` now conflict with that for `I: Iterator + Clone`.

This is due to the changes in https://github.com/rust-lang/rust/pull/23867, in particular the *negative reasoning* as demonstrated in the [`Replacer` example](https://github.com/nikomatsakis/rfcs/blob/rebalancing-coherence/text/0000-rebalancing-coherence.md#user-content-errors-from-cargo-and-the-fundamental-attribute).  

The problem in this case, iiuc, is that `&str` and `&[T]` could one day decide to implement `Iterator`.

**Comment by hawkw** [comment]
:+1:

**Comment by Marwes** [comment]
That's an annoying breaking change. Guess the `Iterator` impl needs to be wrapped in a newtype though it is quite an unergonomic workaround. Still, it feels better than to remove the `&str` and `&[T]` impls since parsing a string directly is so common.

**Comment by Marwes** [comment]
Fixed in c3c54a80c93598f808e0f699e9d543924497b154 and pushed to cargo with 6398c2e0d7ae240df5cc0ef6d363ed310d552f1d  (0.2.6).

I am not sure that these changes are the ideal choice though, might be that the `Stream` trait is better of being only implemented for `Iterator`, essentially making it an `Iterator` with a `Clone` bound
