### ISSUE TITLE
About the unconditional_recursion warning in primitives.rs

### ISSUE THREAD

**Issue by oderwat** [Marwes/parser-combinators#5]
Can you have a look at this please?

https://github.com/rust-lang/rust/issues/21705

Is @huonw right?

**Comment by Marwes** [comment]
Yes he is, there should be another deref there. Never actually tested boxed parsers since I did not have any need for them. Box trait objects should be useful but it seems that there may be another bug for them https://github.com/rust-lang/rust/issues/21379.
Fixed in https://github.com/Marwes/parser-combinators/commit/20d35d26527e9c7edcb5d3632d21bd2b7782d5a7.

**Comment by oderwat** [comment]
OK. Isn't this the same case just above? https://github.com/Marwes/parser-combinators/blob/20d35d26527e9c7edcb5d3632d21bd2b7782d5a7/src/primitives.rs#L227

**Comment by Marwes** [comment]
Nope, there is a &mut P there which gives
*(&mut P)  == P

The bug was because of &mut Box<P>:
*(&mut Box<P>) == Box<P> (which derefs to &mut Box<P> again) 
**(&mut Box<P>) == P

**Comment by oderwat** [comment]
I see. I think I had something like this in some code where I played with box mysqlf and did not recognize this pattern there. Thank you for the explanation!

**Comment by Marwes** [comment]
Lots of edits there sorry, my brain didn't keep up with the typing since I already knew that there is not issue since I am using the &mut P impl in a few places.

**Comment by oderwat** [comment]
What I took out of it is the part that if it is "borrow boxed" there are two * needed to get to the content.
